remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
color_scheme: apprt
logo: "/images/boxes-v3.png"
title: "vscode-apprt-bundles"

aux_links:
  "GitHub Repo":
    - "//github.com/ctjdr/vscode-apprt-bundles"

aux_links_new_tab: true
search_enabled: true
back_to_top: true
back_to_top_text: "Back to top"

plugins:
  - jemoji